[package]
name = "rustbot"
license = "MIT/Apache-2.0"
authors = [ "Conner Bradley <bradley@advtech.ca>" ]
description = "A discord bot that runs whatever rust code is thrown at it"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "rustbot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["macros", "signal", "rt-multi-thread"] }
dotenv = { version = "0.15.0" }
serenity = "0.10.9"
regex = "1.5.4"
base64 = "0.13.0"
process_control = "3.1"
cached = "0.26.2"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/*rustbot", dest = "/opt/rustbot", mode = "0755" },
    { source = "LICENSE*", dest = "/opt/rustbot", doc = true, mode = "0644" },
    { source = "package-readme.txt", dest = "/opt/rustbot/README.txt", doc = true, mode = "0644" }
]