#!/bin/sh
 
# Trampoline utility for decoding b64 commands and running them

# USAGE: trampoline [code] [args]
# where
#   [code]   = base64 encoded code to be run
#   [args]   = base64 args to run with code

# Decode command from args 
cmd_base64=$1
args_base64=$2

# Construct program and run it depending on what [action] is provided
echo ${cmd_base64} | base64 -d > program.rs
runner program.rs $(echo ${args_base64} | base64 -d)