# Automatically rebuild the runner dockerfile if base image changes
name: Regular base image update check
on:
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Update
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1.1.0
        with:
          base-image: rust:alpine
          image: ghcr.io/theconner/rustbot-runner:latest
  do-update:
    needs: [check-update]    
    secrets: inherit
    uses: ./.github/workflows/build-release-container.yml
    with:
      image_name: rustbot-runner
      image_file: runner.Dockerfile
    if: steps.baseupdatecheck.outputs.needs-updating == 'true'
